export enum StoreActions {
  FetchedPets = "FetchedPets",
  FetchedRecommendations = "FetchedRecommendations",
  FetchedToppers = "FetchedToppers",
  GotCustomerId = "GotCustomerId",
  IsLoadingPets = "IsLoadingPets",
  IsLoadingProducts = "IsLoadingProducts",
  PersistPage = "PersistPage",
  PersistPetAndPage = "PersistPetAndPage",
  ThrewError = "ThrewError",
  RedirectToCart = "RedirectToCart",
  ResetPendingPets = "ResetPendingPets",
  SavedPetToCustomer = "SavedPetToCustomer",
  SaveNewPet = "SaveNewPet",
  SavePet = "SavePet",
  SavePendingPet = "SavePendingPet",
  StartFromSaved = "StartFromSaved",
  StartNewPet = "StartNewPet",
}
