import Shopify from "shopify-api-node";

export type ProductsResponse = Array<{
  quantity: number;
  variant: Shopify.IProductVariant;
}>;

export enum KibbleHandle {
  default = "kibble",
  puppy = "kibble-puppy",
  adult = "kibble-adult",
  weight = "kibble-weight-management",
}

export enum Toppers {
  beefLiver = "beef-liver-protein-pack",
  lambLiver = "lamb-liver-protein-pack",
  turkey = "turkey-breast-protein-pack",
  salmon = "wild-caught-salmon-protein-pack",
  rabbit = "rabbit-protein-pack",
  chicken = "chicken-breast-protein-pack",
  varietyClassic = "variety-pack-classic",
  varietyLand = "variety-pack-land-lovers",
  varietySurfTurf = "variety-pack-surf-turf-and-sky",
  varietyFishFowl = "variety-pack-fish-fowl",
}

export const ProteinSkuMap = [
  {
    kibble: "1004",
    toppers: {
      [Toppers.beefLiver]: "830",
      [Toppers.lambLiver]: "822",
      [Toppers.turkey]: "814",
      [Toppers.salmon]: "9038",
      [Toppers.rabbit]: "9064",
      [Toppers.chicken]: "9111",
      [Toppers.varietyClassic]: "806",
      [Toppers.varietyLand]: "9073",
      [Toppers.varietySurfTurf]: "9047",
      [Toppers.varietyFishFowl]: "9211",
    },
  },
  {
    kibble: "1008",
    toppers: {
      [Toppers.beefLiver]: "831",
      [Toppers.lambLiver]: "823",
      [Toppers.turkey]: "815",
      [Toppers.salmon]: "9039",
      [Toppers.rabbit]: "9065",
      [Toppers.chicken]: "9112",
      [Toppers.varietyClassic]: "807",
      [Toppers.varietyLand]: "9074",
      [Toppers.varietySurfTurf]: "9048",
      [Toppers.varietyFishFowl]: "9212",
    },
  },
  {
    kibble: "1012",
    toppers: {
      [Toppers.beefLiver]: "824",
      [Toppers.lambLiver]: "816",
      [Toppers.turkey]: "808",
      [Toppers.salmon]: "9032",
      [Toppers.rabbit]: "9058",
      [Toppers.chicken]: "9113",
      [Toppers.varietyClassic]: "800",
      [Toppers.varietyLand]: "9067",
      [Toppers.varietySurfTurf]: "9041",
      [Toppers.varietyFishFowl]: "9213",
    },
  },
  {
    kibble: "1016",
    toppers: {
      [Toppers.beefLiver]: "825",
      [Toppers.lambLiver]: "817",
      [Toppers.turkey]: "809",
      [Toppers.salmon]: "9033",
      [Toppers.rabbit]: "9059",
      [Toppers.chicken]: "9114",
      [Toppers.varietyClassic]: "801",
      [Toppers.varietyLand]: "9068",
      [Toppers.varietySurfTurf]: "9042",
      [Toppers.varietyFishFowl]: "9214",
    },
  },
  {
    kibble: "1020",
    toppers: {
      [Toppers.beefLiver]: "826",
      [Toppers.lambLiver]: "818",
      [Toppers.turkey]: "810",
      [Toppers.salmon]: "9034",
      [Toppers.rabbit]: "9060",
      [Toppers.chicken]: "9115",
      [Toppers.varietyClassic]: "802",
      [Toppers.varietyLand]: "9069",
      [Toppers.varietySurfTurf]: "9043",
      [Toppers.varietyFishFowl]: "9215",
    },
  },
  {
    kibble: "1024",
    toppers: {
      [Toppers.beefLiver]: "827",
      [Toppers.lambLiver]: "819",
      [Toppers.turkey]: "811",
      [Toppers.salmon]: "9035",
      [Toppers.rabbit]: "9061",
      [Toppers.chicken]: "9116",
      [Toppers.varietyClassic]: "803",
      [Toppers.varietyLand]: "9070",
      [Toppers.varietySurfTurf]: "9044",
      [Toppers.varietyFishFowl]: "9216",
    },
  },
  {
    kibble: "1028",
    toppers: {
      [Toppers.beefLiver]: "828",
      [Toppers.lambLiver]: "820",
      [Toppers.turkey]: "812",
      [Toppers.salmon]: "9036",
      [Toppers.rabbit]: "9062",
      [Toppers.chicken]: "9117",
      [Toppers.varietyClassic]: "804",
      [Toppers.varietyLand]: "9071",
      [Toppers.varietySurfTurf]: "9045",
      [Toppers.varietyFishFowl]: "9217",
    },
  },
  {
    kibble: "1032",
    toppers: {
      [Toppers.beefLiver]: "829",
      [Toppers.lambLiver]: "821",
      [Toppers.turkey]: "813",
      [Toppers.salmon]: "9037",
      [Toppers.rabbit]: "9063",
      [Toppers.chicken]: "9118",
      [Toppers.varietyClassic]: "805",
      [Toppers.varietyLand]: "9072",
      [Toppers.varietySurfTurf]: "9046",
      [Toppers.varietyFishFowl]: "9218",
    },
  },
  {
    kibble: "1036",
    toppers: {
      [Toppers.beefLiver]: "851",
      [Toppers.lambLiver]: "862",
      [Toppers.turkey]: "871",
      [Toppers.salmon]: "9011",
      [Toppers.rabbit]: "9021",
      [Toppers.chicken]: "9119",
      [Toppers.varietyClassic]: "881",
      [Toppers.varietyLand]: "9081",
      [Toppers.varietySurfTurf]: "9091",
      [Toppers.varietyFishFowl]: "9219",
    },
  },
  {
    kibble: "1040",
    toppers: {
      [Toppers.beefLiver]: "852",
      [Toppers.lambLiver]: "862",
      [Toppers.turkey]: "872",
      [Toppers.salmon]: "9012",
      [Toppers.rabbit]: "9022",
      [Toppers.chicken]: "9120",
      [Toppers.varietyClassic]: "882",
      [Toppers.varietyLand]: "9082",
      [Toppers.varietySurfTurf]: "9092",
      [Toppers.varietyFishFowl]: "9220",
    },
  },
  {
    kibble: "2004",
    toppers: {
      [Toppers.beefLiver]: "830",
      [Toppers.lambLiver]: "822",
      [Toppers.turkey]: "814",
      [Toppers.salmon]: "9038",
      [Toppers.rabbit]: "9064",
      [Toppers.chicken]: "9111",
      [Toppers.varietyClassic]: "806",
      [Toppers.varietyLand]: "9073",
      [Toppers.varietySurfTurf]: "9047",
      [Toppers.varietyFishFowl]: "9211",
    },
  },
  {
    kibble: "2008",
    toppers: {
      [Toppers.beefLiver]: "831",
      [Toppers.lambLiver]: "823",
      [Toppers.turkey]: "815",
      [Toppers.salmon]: "9039",
      [Toppers.rabbit]: "9065",
      [Toppers.chicken]: "9112",
      [Toppers.varietyClassic]: "807",
      [Toppers.varietyLand]: "9074",
      [Toppers.varietySurfTurf]: "9048",
      [Toppers.varietyFishFowl]: "9212",
    },
  },
  {
    kibble: "2012",
    toppers: {
      [Toppers.beefLiver]: "824",
      [Toppers.lambLiver]: "816",
      [Toppers.turkey]: "808",
      [Toppers.salmon]: "9032",
      [Toppers.rabbit]: "9058",
      [Toppers.chicken]: "9113",
      [Toppers.varietyClassic]: "800",
      [Toppers.varietyLand]: "9067",
      [Toppers.varietySurfTurf]: "9041",
      [Toppers.varietyFishFowl]: "9213",
    },
  },
  {
    kibble: "2016",
    toppers: {
      [Toppers.beefLiver]: "825",
      [Toppers.lambLiver]: "817",
      [Toppers.turkey]: "809",
      [Toppers.salmon]: "9033",
      [Toppers.rabbit]: "9059",
      [Toppers.chicken]: "9114",
      [Toppers.varietyClassic]: "801",
      [Toppers.varietyLand]: "9068",
      [Toppers.varietySurfTurf]: "9042",
      [Toppers.varietyFishFowl]: "9214",
    },
  },
  {
    kibble: "2020",
    toppers: {
      [Toppers.beefLiver]: "826",
      [Toppers.lambLiver]: "818",
      [Toppers.turkey]: "810",
      [Toppers.salmon]: "9034",
      [Toppers.rabbit]: "9060",
      [Toppers.chicken]: "9115",
      [Toppers.varietyClassic]: "802",
      [Toppers.varietyLand]: "9069",
      [Toppers.varietySurfTurf]: "9043",
      [Toppers.varietyFishFowl]: "9215",
    },
  },
  {
    kibble: "2024",
    toppers: {
      [Toppers.beefLiver]: "827",
      [Toppers.lambLiver]: "819",
      [Toppers.turkey]: "811",
      [Toppers.salmon]: "9035",
      [Toppers.rabbit]: "9061",
      [Toppers.chicken]: "9116",
      [Toppers.varietyClassic]: "803",
      [Toppers.varietyLand]: "9070",
      [Toppers.varietySurfTurf]: "9044",
      [Toppers.varietyFishFowl]: "9216",
    },
  },
  {
    kibble: "2028",
    toppers: {
      [Toppers.beefLiver]: "828",
      [Toppers.lambLiver]: "820",
      [Toppers.turkey]: "812",
      [Toppers.salmon]: "9036",
      [Toppers.rabbit]: "9062",
      [Toppers.chicken]: "9117",
      [Toppers.varietyClassic]: "804",
      [Toppers.varietyLand]: "9071",
      [Toppers.varietySurfTurf]: "9045",
      [Toppers.varietyFishFowl]: "9217",
    },
  },
  {
    kibble: "2032",
    toppers: {
      [Toppers.beefLiver]: "829",
      [Toppers.lambLiver]: "821",
      [Toppers.turkey]: "813",
      [Toppers.salmon]: "9037",
      [Toppers.rabbit]: "9063",
      [Toppers.chicken]: "9118",
      [Toppers.varietyClassic]: "805",
      [Toppers.varietyLand]: "9072",
      [Toppers.varietySurfTurf]: "9046",
      [Toppers.varietyFishFowl]: "9218",
    },
  },
  {
    kibble: "2036",
    toppers: {
      [Toppers.beefLiver]: "851",
      [Toppers.lambLiver]: "862",
      [Toppers.turkey]: "871",
      [Toppers.salmon]: "9011",
      [Toppers.rabbit]: "9021",
      [Toppers.chicken]: "9119",
      [Toppers.varietyClassic]: "881",
      [Toppers.varietyLand]: "9081",
      [Toppers.varietySurfTurf]: "9091",
      [Toppers.varietyFishFowl]: "9219",
    },
  },
  {
    kibble: "2040",
    toppers: {
      [Toppers.beefLiver]: "852",
      [Toppers.lambLiver]: "862",
      [Toppers.turkey]: "872",
      [Toppers.salmon]: "9012",
      [Toppers.rabbit]: "9022",
      [Toppers.chicken]: "9120",
      [Toppers.varietyClassic]: "882",
      [Toppers.varietyLand]: "9082",
      [Toppers.varietySurfTurf]: "9092",
      [Toppers.varietyFishFowl]: "9220",
    },
  },
  {
    kibble: "2304",
    toppers: {
      [Toppers.beefLiver]: "830",
      [Toppers.lambLiver]: "822",
      [Toppers.turkey]: "814",
      [Toppers.salmon]: "9038",
      [Toppers.rabbit]: "9064",
      [Toppers.chicken]: "9111",
      [Toppers.varietyClassic]: "806",
      [Toppers.varietyLand]: "9073",
      [Toppers.varietySurfTurf]: "9047",
      [Toppers.varietyFishFowl]: "9211",
    },
  },
  {
    kibble: "2308",
    toppers: {
      [Toppers.beefLiver]: "831",
      [Toppers.lambLiver]: "823",
      [Toppers.turkey]: "815",
      [Toppers.salmon]: "9039",
      [Toppers.rabbit]: "9065",
      [Toppers.chicken]: "9112",
      [Toppers.varietyClassic]: "807",
      [Toppers.varietyLand]: "9074",
      [Toppers.varietySurfTurf]: "9048",
      [Toppers.varietyFishFowl]: "9212",
    },
  },
  {
    kibble: "2312",
    toppers: {
      [Toppers.beefLiver]: "824",
      [Toppers.lambLiver]: "816",
      [Toppers.turkey]: "808",
      [Toppers.salmon]: "9032",
      [Toppers.rabbit]: "9058",
      [Toppers.chicken]: "9113",
      [Toppers.varietyClassic]: "800",
      [Toppers.varietyLand]: "9067",
      [Toppers.varietySurfTurf]: "9041",
      [Toppers.varietyFishFowl]: "9213",
    },
  },
  {
    kibble: "2316",
    toppers: {
      [Toppers.beefLiver]: "825",
      [Toppers.lambLiver]: "817",
      [Toppers.turkey]: "809",
      [Toppers.salmon]: "9033",
      [Toppers.rabbit]: "9059",
      [Toppers.chicken]: "9114",
      [Toppers.varietyClassic]: "801",
      [Toppers.varietyLand]: "9068",
      [Toppers.varietySurfTurf]: "9042",
      [Toppers.varietyFishFowl]: "9214",
    },
  },
  {
    kibble: "2320",
    toppers: {
      [Toppers.beefLiver]: "826",
      [Toppers.lambLiver]: "818",
      [Toppers.turkey]: "810",
      [Toppers.salmon]: "9034",
      [Toppers.rabbit]: "9060",
      [Toppers.chicken]: "9115",
      [Toppers.varietyClassic]: "802",
      [Toppers.varietyLand]: "9069",
      [Toppers.varietySurfTurf]: "9043",
      [Toppers.varietyFishFowl]: "9215",
    },
  },
  {
    kibble: "2324",
    toppers: {
      [Toppers.beefLiver]: "827",
      [Toppers.lambLiver]: "819",
      [Toppers.turkey]: "811",
      [Toppers.salmon]: "9035",
      [Toppers.rabbit]: "9061",
      [Toppers.chicken]: "9116",
      [Toppers.varietyClassic]: "803",
      [Toppers.varietyLand]: "9070",
      [Toppers.varietySurfTurf]: "9044",
      [Toppers.varietyFishFowl]: "9216",
    },
  },
  {
    kibble: "2328",
    toppers: {
      [Toppers.beefLiver]: "828",
      [Toppers.lambLiver]: "820",
      [Toppers.turkey]: "812",
      [Toppers.salmon]: "9036",
      [Toppers.rabbit]: "9062",
      [Toppers.chicken]: "9117",
      [Toppers.varietyClassic]: "804",
      [Toppers.varietyLand]: "9071",
      [Toppers.varietySurfTurf]: "9045",
      [Toppers.varietyFishFowl]: "9217",
    },
  },
  {
    kibble: "2332",
    toppers: {
      [Toppers.beefLiver]: "829",
      [Toppers.lambLiver]: "821",
      [Toppers.turkey]: "813",
      [Toppers.salmon]: "9037",
      [Toppers.rabbit]: "9063",
      [Toppers.chicken]: "9118",
      [Toppers.varietyClassic]: "805",
      [Toppers.varietyLand]: "9072",
      [Toppers.varietySurfTurf]: "9046",
      [Toppers.varietyFishFowl]: "9218",
    },
  },
  {
    kibble: "2336",
    toppers: {
      [Toppers.beefLiver]: "851",
      [Toppers.lambLiver]: "862",
      [Toppers.turkey]: "871",
      [Toppers.salmon]: "9011",
      [Toppers.rabbit]: "9021",
      [Toppers.chicken]: "9119",
      [Toppers.varietyClassic]: "881",
      [Toppers.varietyLand]: "9081",
      [Toppers.varietySurfTurf]: "9091",
      [Toppers.varietyFishFowl]: "9219",
    },
  },
  {
    kibble: "2340",
    toppers: {
      [Toppers.beefLiver]: "852",
      [Toppers.lambLiver]: "862",
      [Toppers.turkey]: "872",
      [Toppers.salmon]: "9012",
      [Toppers.rabbit]: "9022",
      [Toppers.chicken]: "9120",
      [Toppers.varietyClassic]: "882",
      [Toppers.varietyLand]: "9082",
      [Toppers.varietySurfTurf]: "9092",
      [Toppers.varietyFishFowl]: "9220",
    },
  },
];
