import Shopify from "shopify-api-node";

export type ProductsResponse = Array<{
  quantity: number;
  variant: Shopify.IProductVariant;
}>;

export enum KibbleHandle {
  DEFAULT = "kibble",
  PUPPY = "kibble-puppy",
  ADULT = "kibble-adult",
  WEIGHT = "kibble-weight-management",
}

export enum Toppers {
  BEEF_LIVER = "beef-liver-protein-pack",
  LAMB_LIVER = "lamb-liver-protein-pack",
  TURKEY = "turkey-breast-protein-pack",
  SALMON = "wild-caught-salmon-protein-pack",
  RABBIT = "rabbit-protein-pack",
  CHICKEN = "chicken-breast-protein-pack",
  VARIETY_CLASSIC = "variety-pack-classic",
  VARIETY_LAND = "variety-pack-land-lovers",
  VARIETY_SURF_TURN = "variety-pack-surf-turf-and-sky",
  VARIETY_FISH_FOWL = "variety-pack-fish-fowl",
}

export const ProteinSkuMap = [
  {
    kibble: "1004",
    toppers: {
      [Toppers.BEEF_LIVER]: "830",
      [Toppers.LAMB_LIVER]: "822",
      [Toppers.TURKEY]: "814",
      [Toppers.SALMON]: "9038",
      [Toppers.RABBIT]: "9064",
      [Toppers.CHICKEN]: "9111",
      [Toppers.VARIETY_CLASSIC]: "806",
      [Toppers.VARIETY_LAND]: "9073",
      [Toppers.VARIETY_SURF_TURN]: "9047",
      [Toppers.VARIETY_FISH_FOWL]: "9211",
    },
  },
  {
    kibble: "1008",
    toppers: {
      [Toppers.BEEF_LIVER]: "831",
      [Toppers.LAMB_LIVER]: "823",
      [Toppers.TURKEY]: "815",
      [Toppers.SALMON]: "9039",
      [Toppers.RABBIT]: "9065",
      [Toppers.CHICKEN]: "9112",
      [Toppers.VARIETY_CLASSIC]: "807",
      [Toppers.VARIETY_LAND]: "9074",
      [Toppers.VARIETY_SURF_TURN]: "9048",
      [Toppers.VARIETY_FISH_FOWL]: "9212",
    },
  },
  {
    kibble: "1012",
    toppers: {
      [Toppers.BEEF_LIVER]: "824",
      [Toppers.LAMB_LIVER]: "816",
      [Toppers.TURKEY]: "808",
      [Toppers.SALMON]: "9032",
      [Toppers.RABBIT]: "9058",
      [Toppers.CHICKEN]: "9113",
      [Toppers.VARIETY_CLASSIC]: "800",
      [Toppers.VARIETY_LAND]: "9067",
      [Toppers.VARIETY_SURF_TURN]: "9041",
      [Toppers.VARIETY_FISH_FOWL]: "9213",
    },
  },
  {
    kibble: "1016",
    toppers: {
      [Toppers.BEEF_LIVER]: "825",
      [Toppers.LAMB_LIVER]: "817",
      [Toppers.TURKEY]: "809",
      [Toppers.SALMON]: "9033",
      [Toppers.RABBIT]: "9059",
      [Toppers.CHICKEN]: "9114",
      [Toppers.VARIETY_CLASSIC]: "801",
      [Toppers.VARIETY_LAND]: "9068",
      [Toppers.VARIETY_SURF_TURN]: "9042",
      [Toppers.VARIETY_FISH_FOWL]: "9214",
    },
  },
  {
    kibble: "1020",
    toppers: {
      [Toppers.BEEF_LIVER]: "826",
      [Toppers.LAMB_LIVER]: "818",
      [Toppers.TURKEY]: "810",
      [Toppers.SALMON]: "9034",
      [Toppers.RABBIT]: "9060",
      [Toppers.CHICKEN]: "9115",
      [Toppers.VARIETY_CLASSIC]: "802",
      [Toppers.VARIETY_LAND]: "9069",
      [Toppers.VARIETY_SURF_TURN]: "9043",
      [Toppers.VARIETY_FISH_FOWL]: "9215",
    },
  },
  {
    kibble: "1024",
    toppers: {
      [Toppers.BEEF_LIVER]: "827",
      [Toppers.LAMB_LIVER]: "819",
      [Toppers.TURKEY]: "811",
      [Toppers.SALMON]: "9035",
      [Toppers.RABBIT]: "9061",
      [Toppers.CHICKEN]: "9116",
      [Toppers.VARIETY_CLASSIC]: "803",
      [Toppers.VARIETY_LAND]: "9070",
      [Toppers.VARIETY_SURF_TURN]: "9044",
      [Toppers.VARIETY_FISH_FOWL]: "9216",
    },
  },
  {
    kibble: "1028",
    toppers: {
      [Toppers.BEEF_LIVER]: "828",
      [Toppers.LAMB_LIVER]: "820",
      [Toppers.TURKEY]: "812",
      [Toppers.SALMON]: "9036",
      [Toppers.RABBIT]: "9062",
      [Toppers.CHICKEN]: "9117",
      [Toppers.VARIETY_CLASSIC]: "804",
      [Toppers.VARIETY_LAND]: "9071",
      [Toppers.VARIETY_SURF_TURN]: "9045",
      [Toppers.VARIETY_FISH_FOWL]: "9217",
    },
  },
  {
    kibble: "1032",
    toppers: {
      [Toppers.BEEF_LIVER]: "829",
      [Toppers.LAMB_LIVER]: "821",
      [Toppers.TURKEY]: "813",
      [Toppers.SALMON]: "9037",
      [Toppers.RABBIT]: "9063",
      [Toppers.CHICKEN]: "9118",
      [Toppers.VARIETY_CLASSIC]: "805",
      [Toppers.VARIETY_LAND]: "9072",
      [Toppers.VARIETY_SURF_TURN]: "9046",
      [Toppers.VARIETY_FISH_FOWL]: "9218",
    },
  },
  {
    kibble: "1036",
    toppers: {
      [Toppers.BEEF_LIVER]: "851",
      [Toppers.LAMB_LIVER]: "862",
      [Toppers.TURKEY]: "871",
      [Toppers.SALMON]: "9011",
      [Toppers.RABBIT]: "9021",
      [Toppers.CHICKEN]: "9119",
      [Toppers.VARIETY_CLASSIC]: "881",
      [Toppers.VARIETY_LAND]: "9081",
      [Toppers.VARIETY_SURF_TURN]: "9091",
      [Toppers.VARIETY_FISH_FOWL]: "9219",
    },
  },
  {
    kibble: "1040",
    toppers: {
      [Toppers.BEEF_LIVER]: "852",
      [Toppers.LAMB_LIVER]: "862",
      [Toppers.TURKEY]: "872",
      [Toppers.SALMON]: "9012",
      [Toppers.RABBIT]: "9022",
      [Toppers.CHICKEN]: "9120",
      [Toppers.VARIETY_CLASSIC]: "882",
      [Toppers.VARIETY_LAND]: "9082",
      [Toppers.VARIETY_SURF_TURN]: "9092",
      [Toppers.VARIETY_FISH_FOWL]: "9220",
    },
  },
  {
    kibble: "2004",
    toppers: {
      [Toppers.BEEF_LIVER]: "830",
      [Toppers.LAMB_LIVER]: "822",
      [Toppers.TURKEY]: "814",
      [Toppers.SALMON]: "9038",
      [Toppers.RABBIT]: "9064",
      [Toppers.CHICKEN]: "9111",
      [Toppers.VARIETY_CLASSIC]: "806",
      [Toppers.VARIETY_LAND]: "9073",
      [Toppers.VARIETY_SURF_TURN]: "9047",
      [Toppers.VARIETY_FISH_FOWL]: "9211",
    },
  },
  {
    kibble: "2008",
    toppers: {
      [Toppers.BEEF_LIVER]: "831",
      [Toppers.LAMB_LIVER]: "823",
      [Toppers.TURKEY]: "815",
      [Toppers.SALMON]: "9039",
      [Toppers.RABBIT]: "9065",
      [Toppers.CHICKEN]: "9112",
      [Toppers.VARIETY_CLASSIC]: "807",
      [Toppers.VARIETY_LAND]: "9074",
      [Toppers.VARIETY_SURF_TURN]: "9048",
      [Toppers.VARIETY_FISH_FOWL]: "9212",
    },
  },
  {
    kibble: "2012",
    toppers: {
      [Toppers.BEEF_LIVER]: "824",
      [Toppers.LAMB_LIVER]: "816",
      [Toppers.TURKEY]: "808",
      [Toppers.SALMON]: "9032",
      [Toppers.RABBIT]: "9058",
      [Toppers.CHICKEN]: "9113",
      [Toppers.VARIETY_CLASSIC]: "800",
      [Toppers.VARIETY_LAND]: "9067",
      [Toppers.VARIETY_SURF_TURN]: "9041",
      [Toppers.VARIETY_FISH_FOWL]: "9213",
    },
  },
  {
    kibble: "2016",
    toppers: {
      [Toppers.BEEF_LIVER]: "825",
      [Toppers.LAMB_LIVER]: "817",
      [Toppers.TURKEY]: "809",
      [Toppers.SALMON]: "9033",
      [Toppers.RABBIT]: "9059",
      [Toppers.CHICKEN]: "9114",
      [Toppers.VARIETY_CLASSIC]: "801",
      [Toppers.VARIETY_LAND]: "9068",
      [Toppers.VARIETY_SURF_TURN]: "9042",
      [Toppers.VARIETY_FISH_FOWL]: "9214",
    },
  },
  {
    kibble: "2020",
    toppers: {
      [Toppers.BEEF_LIVER]: "826",
      [Toppers.LAMB_LIVER]: "818",
      [Toppers.TURKEY]: "810",
      [Toppers.SALMON]: "9034",
      [Toppers.RABBIT]: "9060",
      [Toppers.CHICKEN]: "9115",
      [Toppers.VARIETY_CLASSIC]: "802",
      [Toppers.VARIETY_LAND]: "9069",
      [Toppers.VARIETY_SURF_TURN]: "9043",
      [Toppers.VARIETY_FISH_FOWL]: "9215",
    },
  },
  {
    kibble: "2024",
    toppers: {
      [Toppers.BEEF_LIVER]: "827",
      [Toppers.LAMB_LIVER]: "819",
      [Toppers.TURKEY]: "811",
      [Toppers.SALMON]: "9035",
      [Toppers.RABBIT]: "9061",
      [Toppers.CHICKEN]: "9116",
      [Toppers.VARIETY_CLASSIC]: "803",
      [Toppers.VARIETY_LAND]: "9070",
      [Toppers.VARIETY_SURF_TURN]: "9044",
      [Toppers.VARIETY_FISH_FOWL]: "9216",
    },
  },
  {
    kibble: "2028",
    toppers: {
      [Toppers.BEEF_LIVER]: "828",
      [Toppers.LAMB_LIVER]: "820",
      [Toppers.TURKEY]: "812",
      [Toppers.SALMON]: "9036",
      [Toppers.RABBIT]: "9062",
      [Toppers.CHICKEN]: "9117",
      [Toppers.VARIETY_CLASSIC]: "804",
      [Toppers.VARIETY_LAND]: "9071",
      [Toppers.VARIETY_SURF_TURN]: "9045",
      [Toppers.VARIETY_FISH_FOWL]: "9217",
    },
  },
  {
    kibble: "2032",
    toppers: {
      [Toppers.BEEF_LIVER]: "829",
      [Toppers.LAMB_LIVER]: "821",
      [Toppers.TURKEY]: "813",
      [Toppers.SALMON]: "9037",
      [Toppers.RABBIT]: "9063",
      [Toppers.CHICKEN]: "9118",
      [Toppers.VARIETY_CLASSIC]: "805",
      [Toppers.VARIETY_LAND]: "9072",
      [Toppers.VARIETY_SURF_TURN]: "9046",
      [Toppers.VARIETY_FISH_FOWL]: "9218",
    },
  },
  {
    kibble: "2036",
    toppers: {
      [Toppers.BEEF_LIVER]: "851",
      [Toppers.LAMB_LIVER]: "862",
      [Toppers.TURKEY]: "871",
      [Toppers.SALMON]: "9011",
      [Toppers.RABBIT]: "9021",
      [Toppers.CHICKEN]: "9119",
      [Toppers.VARIETY_CLASSIC]: "881",
      [Toppers.VARIETY_LAND]: "9081",
      [Toppers.VARIETY_SURF_TURN]: "9091",
      [Toppers.VARIETY_FISH_FOWL]: "9219",
    },
  },
  {
    kibble: "2040",
    toppers: {
      [Toppers.BEEF_LIVER]: "852",
      [Toppers.LAMB_LIVER]: "862",
      [Toppers.TURKEY]: "872",
      [Toppers.SALMON]: "9012",
      [Toppers.RABBIT]: "9022",
      [Toppers.CHICKEN]: "9120",
      [Toppers.VARIETY_CLASSIC]: "882",
      [Toppers.VARIETY_LAND]: "9082",
      [Toppers.VARIETY_SURF_TURN]: "9092",
      [Toppers.VARIETY_FISH_FOWL]: "9220",
    },
  },
  {
    kibble: "2304",
    toppers: {
      [Toppers.BEEF_LIVER]: "830",
      [Toppers.LAMB_LIVER]: "822",
      [Toppers.TURKEY]: "814",
      [Toppers.SALMON]: "9038",
      [Toppers.RABBIT]: "9064",
      [Toppers.CHICKEN]: "9111",
      [Toppers.VARIETY_CLASSIC]: "806",
      [Toppers.VARIETY_LAND]: "9073",
      [Toppers.VARIETY_SURF_TURN]: "9047",
      [Toppers.VARIETY_FISH_FOWL]: "9211",
    },
  },
  {
    kibble: "2308",
    toppers: {
      [Toppers.BEEF_LIVER]: "831",
      [Toppers.LAMB_LIVER]: "823",
      [Toppers.TURKEY]: "815",
      [Toppers.SALMON]: "9039",
      [Toppers.RABBIT]: "9065",
      [Toppers.CHICKEN]: "9112",
      [Toppers.VARIETY_CLASSIC]: "807",
      [Toppers.VARIETY_LAND]: "9074",
      [Toppers.VARIETY_SURF_TURN]: "9048",
      [Toppers.VARIETY_FISH_FOWL]: "9212",
    },
  },
  {
    kibble: "2312",
    toppers: {
      [Toppers.BEEF_LIVER]: "824",
      [Toppers.LAMB_LIVER]: "816",
      [Toppers.TURKEY]: "808",
      [Toppers.SALMON]: "9032",
      [Toppers.RABBIT]: "9058",
      [Toppers.CHICKEN]: "9113",
      [Toppers.VARIETY_CLASSIC]: "800",
      [Toppers.VARIETY_LAND]: "9067",
      [Toppers.VARIETY_SURF_TURN]: "9041",
      [Toppers.VARIETY_FISH_FOWL]: "9213",
    },
  },
  {
    kibble: "2316",
    toppers: {
      [Toppers.BEEF_LIVER]: "825",
      [Toppers.LAMB_LIVER]: "817",
      [Toppers.TURKEY]: "809",
      [Toppers.SALMON]: "9033",
      [Toppers.RABBIT]: "9059",
      [Toppers.CHICKEN]: "9114",
      [Toppers.VARIETY_CLASSIC]: "801",
      [Toppers.VARIETY_LAND]: "9068",
      [Toppers.VARIETY_SURF_TURN]: "9042",
      [Toppers.VARIETY_FISH_FOWL]: "9214",
    },
  },
  {
    kibble: "2320",
    toppers: {
      [Toppers.BEEF_LIVER]: "826",
      [Toppers.LAMB_LIVER]: "818",
      [Toppers.TURKEY]: "810",
      [Toppers.SALMON]: "9034",
      [Toppers.RABBIT]: "9060",
      [Toppers.CHICKEN]: "9115",
      [Toppers.VARIETY_CLASSIC]: "802",
      [Toppers.VARIETY_LAND]: "9069",
      [Toppers.VARIETY_SURF_TURN]: "9043",
      [Toppers.VARIETY_FISH_FOWL]: "9215",
    },
  },
  {
    kibble: "2324",
    toppers: {
      [Toppers.BEEF_LIVER]: "827",
      [Toppers.LAMB_LIVER]: "819",
      [Toppers.TURKEY]: "811",
      [Toppers.SALMON]: "9035",
      [Toppers.RABBIT]: "9061",
      [Toppers.CHICKEN]: "9116",
      [Toppers.VARIETY_CLASSIC]: "803",
      [Toppers.VARIETY_LAND]: "9070",
      [Toppers.VARIETY_SURF_TURN]: "9044",
      [Toppers.VARIETY_FISH_FOWL]: "9216",
    },
  },
  {
    kibble: "2328",
    toppers: {
      [Toppers.BEEF_LIVER]: "828",
      [Toppers.LAMB_LIVER]: "820",
      [Toppers.TURKEY]: "812",
      [Toppers.SALMON]: "9036",
      [Toppers.RABBIT]: "9062",
      [Toppers.CHICKEN]: "9117",
      [Toppers.VARIETY_CLASSIC]: "804",
      [Toppers.VARIETY_LAND]: "9071",
      [Toppers.VARIETY_SURF_TURN]: "9045",
      [Toppers.VARIETY_FISH_FOWL]: "9217",
    },
  },
  {
    kibble: "2332",
    toppers: {
      [Toppers.BEEF_LIVER]: "829",
      [Toppers.LAMB_LIVER]: "821",
      [Toppers.TURKEY]: "813",
      [Toppers.SALMON]: "9037",
      [Toppers.RABBIT]: "9063",
      [Toppers.CHICKEN]: "9118",
      [Toppers.VARIETY_CLASSIC]: "805",
      [Toppers.VARIETY_LAND]: "9072",
      [Toppers.VARIETY_SURF_TURN]: "9046",
      [Toppers.VARIETY_FISH_FOWL]: "9218",
    },
  },
  {
    kibble: "2336",
    toppers: {
      [Toppers.BEEF_LIVER]: "851",
      [Toppers.LAMB_LIVER]: "862",
      [Toppers.TURKEY]: "871",
      [Toppers.SALMON]: "9011",
      [Toppers.RABBIT]: "9021",
      [Toppers.CHICKEN]: "9119",
      [Toppers.VARIETY_CLASSIC]: "881",
      [Toppers.VARIETY_LAND]: "9081",
      [Toppers.VARIETY_SURF_TURN]: "9091",
      [Toppers.VARIETY_FISH_FOWL]: "9219",
    },
  },
  {
    kibble: "2340",
    toppers: {
      [Toppers.BEEF_LIVER]: "852",
      [Toppers.LAMB_LIVER]: "862",
      [Toppers.TURKEY]: "872",
      [Toppers.SALMON]: "9012",
      [Toppers.RABBIT]: "9022",
      [Toppers.CHICKEN]: "9120",
      [Toppers.VARIETY_CLASSIC]: "882",
      [Toppers.VARIETY_LAND]: "9082",
      [Toppers.VARIETY_SURF_TURN]: "9092",
      [Toppers.VARIETY_FISH_FOWL]: "9220",
    },
  },
];
